# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G

# Fabric Properties
	# check these on https://fabricmc.net/develop/
	minecraft_version = 26.2
	loader_version = 0.19.3

# Mod Properties
	mod_version = 0.4.0
	maven_group = velizarbg.buildevents
	archives_base_name = buildevents
	modrinth_id = fzSM8IMo
	curseforge_id = 937098

# Fabric Mod Metadata
	minecraft_dependency = >=26.2
	loader_dependency = >=0.17.0

# Build Information
# The target mc versions for the mod during mod publishing
	title_version = 26.2
	release_versions = 26.2

# Dev Dependencies
	loom_version = 1.17.17
	mod_publish_version = 2.1.+

# Dependencies
	fabric_api_version = 0.155.2+26.2
	server_translations = 3.1.0+26.2
