# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.21.11
	yarn_mappings=1.21.11+build.5
	loader_version=0.19.2

# Mod Properties
	mod_version = 0.4.1
	maven_group = velizarbg.buildevents
	archives_base_name = buildevents
	modrinth_id = fzSM8IMo
	curseforge_id = 937098

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.141.4+1.21.11
	server_translations=2.5.2+1.21.9-pre3
