pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        mavenCentral()
        gradlePluginPortal()
    }

    plugins {
        id 'net.fabricmc.fabric-loom-remap' version loom_version
        id 'me.modmuss50.mod-publish-plugin' version mod_publish_version
    }
}
